name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    outputs:
      mirabel_sys: ${{ steps.mirabel_sys.outputs.rev }}
    steps:
      - uses: actions/checkout@v3
      - name: Get date
        id: get-date
        # purge cache weekly to refresh updated dependencies
        run: echo "date=$(date -u "+%Y-%W")" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/
            ~/.cargo/.*
            target/
          key: "${{ runner.os }}-cargo-${{ steps.get-date.outputs.date }}\
            -${{ hashFiles('Cargo.toml') }}"
      - name: Build
        run: cargo build --verbose
      - uses: actions/upload-artifact@v3
        with:
          name: example
          path: target/debug/libexample.so
      - name: Install cargo-lock
        run: cargo install cargo-lock --version=8.0.3 --features=cli
      # find out mirabel_sys commit hash via cargo-lock
      - name: Get mirabel_sys revision
        id: mirabel_sys
        run: >-
          echo "rev=$(cargo lock --sources --package mirabel_sys | sed -rn
          's/^.+rev=([a-f0-9]+)#\1\)$/\1/p')" >> $GITHUB_OUTPUT
      - name: Test
        timeout-minutes: 5
        run: cargo test --verbose
      - name: Clippy
        run: cargo clippy --no-deps -- --deny=warnings

  surena:
    name: Surena integration test
    runs-on: ubuntu-latest
    needs: build
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: vilaureu/mirabel_sys
          ref: ${{ needs.build.outputs.mirabel_sys }}
          submodules: recursive
      - name: Get surena commit
        id: get-surena
        # purge cache on submodule update
        run: echo "commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
        working-directory: mirabel/lib/surena
      - uses: actions/cache@v3
        id: cache
        with:
          path: build/
          key: ${{ runner.os }}-surena-${{ steps.get-surena.outputs.commit }}
      - name: Touch build to prevent CMake from recompiling
        if: steps.cache.outputs.cache-hit == 'true'
        run: find build -exec touch {} +
      - uses: actions/download-artifact@v3
        with:
          name: example
      - name: Make libexample.so executable
        run: chmod +x libexample.so
      - name: Configure
        # GCC-9 crashes when compiling surena
        run: >-
          cmake -S mirabel/lib/surena -B build -DCMAKE_BUILD_TYPE=Debug
          -DCMAKE_C_COMPILER=/usr/bin/gcc-10
          -DCMAKE_CXX_COMPILER=/usr/bin/g++-10
      - name: Build
        run: cmake --build build
      - name: Test
        timeout-minutes: 5
        run: >-
          echo -e "5\ninvalid\n4\n2\n1" | ./build/surena --game-plugin
          ./libexample.so --game-options "10 5"
